# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # match(type: "appstore")
    # increment_build_number(xcodeproj: "YelpPeru.xcodeproj")
    # build_app(workspace: "YelpPeru.xcworkspace", scheme: "YelpPeru")
    upload_to_testflight(
      itc_provider: "G89HVVK364", # pass a specific value to the iTMSTransporter -itc_provider option
      skip_waiting_for_build_processing: true
    )
    clean_build_artifacts
    commit_version_bump(
      message: "Fastlane iOS: Released new build #{lane_context[SharedValues::BUILD_NUMBER]} [ci skip]",
      xcodeproj: "./YelpPeru.xcworkspace",
      force: true
    )
  end
end
